/* eslint-disable @typescript-eslint/no-explicit-any */
export interface Creator {
  id: string;
  uid: string;
  createdAt: any;
  username: string;
  bio?: string;
  website?: string;
  verified: boolean;
  network: string;
  payoutNumber: string;
  name: string;
  location?: string;
  handle: string;
  bannerURL?: string;
  photoURL?: string;
  totalEarnings: number;
  totalEarningsUSD?: number;
  totalSupporters: number;
  pendingPayout: number;
  pendingPayoutUSD?: number;
  socials: {
    instagram: string | null;
    linkedin: string | null;
    twitter: string | null;
    youtube: string | null;
    tiktok: string | null;
    web: string | null;
  };
  perks: Array<any>;
  events: Array<any>;
  views: number;
  lastPayoutAt?: any;
  verificationStatus: "pending" | "approved" | "rejected";
  phoneVerified: boolean;
  foundingMember: boolean;
  profilePicture: string;
  messagingEnabled?: boolean;
  messagingAllowAll?: boolean;
  messagingMinAmount?: number;
  storeEnabled?: boolean;
  storePublic?: boolean;
  giveawayEnabled?: boolean;
  bookingEnabled?: boolean;
  bookingAccess?: "public" | "supporters";
  bookingAvailability?: import("./booking").BookingAvailability;
  bookingMode?: "simple" | "tiered";
  bookingTiers?: import("./booking").BookingTier[];
  gatheringsEnabled?: boolean;
  communityEnabled?: boolean;
  communityTiers?: import("./community").CommunityTier[];
  focus?: string[];
  country?: string;
  currency?: string;
}
